# Generated by Django 3.0.3 on 2020-03-14 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('background_task', '0002_auto_20170927_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('figi', models.CharField(db_index=True, max_length=20, unique=True)),
                ('ticker', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('type', models.CharField(max_length=20)),
                ('isin', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Инструмент',
                'verbose_name_plural': 'Инструменты',
            },
        ),
        migrations.CreateModel(
            name='GetDataTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80)),
                ('from', models.DateTimeField(null=True)),
                ('to', models.DateTimeField(null=True)),
                ('interval', models.CharField(max_length=10, null=True)),
                ('figi', models.CharField(max_length=20, null=True)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('end_at', models.DateTimeField(default=None, null=True)),
                ('succeeded', models.BooleanField(default=None, null=True)),
                ('background_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_data_tasks', to='background_task.Task')),
            ],
            options={
                'verbose_name': 'Прокси-задача',
                'verbose_name_plural': 'Прокси-задачи',
            },
        ),
        migrations.CreateModel(
            name='Candle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(db_index=True)),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('interval', models.CharField(db_index=True, max_length=10)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candles', to='analysis.Instrument')),
            ],
            options={
                'verbose_name': 'Котировка',
                'verbose_name_plural': 'Котировки',
            },
        ),
    ]
