# Generated by Django 3.0.3 on 2020-03-09 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candle',
            name='interval',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='candle',
            name='time',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='figi',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='isin',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='ticker',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
