# Generated by Django 3.0.3 on 2020-03-07 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Candles',
            new_name='Candle',
        ),
        migrations.AlterModelOptions(
            name='candle',
            options={'verbose_name': 'Котировка', 'verbose_name_plural': 'Котировки'},
        ),
        migrations.AlterModelOptions(
            name='instrument',
            options={'verbose_name': 'Инструмент', 'verbose_name_plural': 'Инструменты'},
        ),
    ]
