# Generated by Django 3.0.3 on 2020-03-14 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('background_task', '0002_auto_20170927_1109'),
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getdatatask',
            name='background_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_data_tasks', to='background_task.Task'),
        ),
    ]
