# Generated by Django 3.0.3 on 2020-03-09 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('background_task', '0002_auto_20170927_1109'),
        ('analysis', '0002_auto_20200309_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskProxy',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='background_task.Task')),
                ('action', models.CharField(max_length=80)),
                ('_from', models.DateTimeField(null=True)),
                ('to', models.DateTimeField(null=True)),
                ('interval', models.CharField(max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Прокси-задача',
                'verbose_name_plural': 'Прокси-задачи',
            },
            bases=('background_task.task',),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='figi',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
    ]
