# Generated by Django 3.0.3 on 2020-03-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_auto_20200314_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='getdatatask',
            name='started_at',
            field=models.DateTimeField(null=True),
        ),
    ]
