# Generated by Django 3.0.3 on 2020-03-14 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_getdatatask_started_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='getdatatask',
            old_name='from',
            new_name='from_time',
        ),
        migrations.RenameField(
            model_name='getdatatask',
            old_name='to',
            new_name='to_time',
        ),
    ]
