# Generated by Django 3.0.3 on 2020-03-09 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_auto_20200309_1704'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskproxy',
            old_name='_from',
            new_name='from',
        ),
    ]
