# Generated by Django 3.0.3 on 2020-03-09 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_auto_20200309_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskproxy',
            name='figi',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
